spring:
  datasource:
    url: jdbc:mysql://${docker_prod_db_host}:${db_port}/${docker_prod_db_name}
    username: ${docker_prod_db_user}
    password: ${docker_prod_db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${docker_prod_cache_host}
      port: ${docker_prod_cache_port}

cookie:
  secure: true
  samesite: ${docker_prod_cookie_samesite:Strict}
  domain: ${docker_prod_cookie_domain:.leafresh.app}

gcp:
  project-id: ${gcp_project_id}
  credentials:
    location: classpath:${gcp_credentials_location}
  storage:
    bucket: ${gcp_storage_bucket}
